### ISSUE TITLE
Implement forecast-hourly

### ISSUE THREAD

**Issue by Mafeuser** [cadadr/forecast.el#7]
(forecast) invoked by (forecast-hourly) overwrites:
(setf forecast--hourly-mode nil)

Even after fixing this, I do not get per hour weather forecast, just descriptive info:

9°C - Mostly Cloudy
Feels like 6, Light rain overnight.
>------------------------<
Pressure 0.993 atm; Humidity 81.0%
Wind 5.04 m/s, from SW

Is it what forecast-hourly should look like?

regards

**Comment by cadadr** [comment]
Whoops sorry, that's not yet implemented.  The function `forecast--insert-hourly-forecast` which is supposed to set up the view has to be implemented.  I'll sort it out when I have time.  My bad, I should have not committed it to master  (P.S. pull request welcome if you wish to, I'm a bit short of time nowadays, because university).

**Comment by cadadr** [comment]
I have implemented `forecast-hourly` as a 24-hour dot graphic that appears above the upcoming forecasts, as part of v0.4.0.  @Mafeuser I hope it will be useful to you, sorry for the delay.
